### ISSUE TITLE
Add GraalVM flavor as base container image

### ISSUE THREAD

**Issue by XhstormR** [gradle/docker-gradle#253]
It would be great if we have gradle image with GraalVM.

FYI:
https://github.com/graalvm/graalvm-ce-builds/releases/tag/jdk-20.0.2
https://github.com/graalvm/container

**Comment by keeganwitt** [comment]
Forgive the ignorance (I'm not a Graal user), but isn't Graal only needed for runtime and not build time?

Another challenge I'd have for implementing this request is that as an official image, I'm only allowed to extend other official images, and I [don't see one for Graal](https://github.com/search?q=repo%3Adocker-library%2Fofficial-images%20graal&type=code).

**Comment by XhstormR** [comment]
@keeganwitt  According to this PR https://github.com/oracle/graal/pull/5995 , Native Image is now shipped as part of the GraalVM JDK and thus no longer needs to be installed via gu install native-image. So we can use native-image tools to directly convert the jar file into a native executable file after the gradle build is complete.

**Comment by keeganwitt** [comment]
Adding link here for posterity: the idea of an official GraalVM image was rejected previously.
https://github.com/docker-library/official-images/pull/10936

**Comment by keeganwitt** [comment]
Official images PR: https://github.com/docker-library/official-images/pull/15196
